=== ahhyoushh/ahhyoushh.github.io/.astro/collections/blogs.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "link": {
      "type": "string"
    },
    "date": {
      "type": "string"
    },
    "$schema": {
      "type": "string"
    }
  },
  "required": [
    "title",
    "description",
    "link"
  ]
}

=== ahhyoushh/ahhyoushh.github.io/blogs.json
[
  {
    "title": "making an actual realtime prediction market",
    "description": "understanding realtime,the evolution from polling to websockets, and from sigmoid functions to binary lmsr",
    "link": "/blogs/betjee_v2",
    "date": "mar 2026"
  },
  {
    "title": "making a prediction market",
    "description": "how i made a prediction market for jee shifts withing 24hours and realisation how trash it was",
    "link": "/blogs/betjee",
    "date": "feb 2026"
  },
  {
    "title": "effect of diwali on aqi",
    "description": "made a simple aqi predicting linear regression model and accidentally found out how bad diwali affects AQI",
    "link": "/blogs/DiwaliAQI",
    "date": "dec 2025"
  }
]
